---
- name: Installing Apache
  ansible.builtin.yum:
    name: httpd
    state: installed

- name: Start and enable Apache
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: Copy and paste html file
  ansible.builtin.copy:
    src: newindex.html
    dest: /var/www/html/index.html
...

